#!/usr/bin/python3

import sys
from src.display_help import display_help


def main(argv: list[str]) -> int:
    if len(argv) == 2 and argv[1] == "-h":
        return display_help()
    #check_arg(argv[1:])
    return 0

if __name__ == "__main__":
    sys.exit(main(sys.argv))
