#!/usr/bin/python3

import sys
from src.check_arg import check_arg

def main(argv: list[str]) -> int:
    if len(argv) == 2 and argv[1] == "-h":
        return 0
    #return display_usage()
    check_arg(argv[1:])
    return 0

if __name__ == "__main__":
    sys.exit(main(sys.argv))
